batch_size: 30
beta1: 0.75
compute_SSIM_anyway: false
config: configs/train_conf_utnet_std.yaml
cs: 184
xpu_device: 0
d2_activation: PReLU
d2_funit: 32
d2_loss_function: MSE
d2_lr: null
d2_model_path: null
d2_network: null
d_activation: PReLU
d_funit: 32
d_loss_function: MSE
d_lr: null
d_model_path: null
d_network: null
debug_options:
- output_val_images
discriminator2_advantage: 0.0
discriminator_advantage: 0.0
epochs: 1000
exp_mult_max: 1.15
exp_mult_min: 0.85
freeze_generator: false
g_activation: Hardswish
g_funit: 64
g_lr: 0.0003
g_model_path: null
g_network: UtNet
loss_cs: 184
min_crop_size: null
min_lr: 5.0e-08
models_dpath: ../../models/nind_denoise
not_conditional: false
not_conditional_2: false
orig_data: ../../datasets/NIND
patience: 3
reduce_lr_factor: 0.95
start_epoch: 1
test_interval: 0
test_reserve:
- ursulines-red
- stefantiek
- ursulines-building
- MuseeL-Bobo
- CourtineDeVillersDebris
- MuseeL-Bobo-C500D
- Pen-pile
threads: 8
time_limit: null
train_data:
- ../../datasets/cropped/NIND_256_192
validation_interval: 1
validation_set_yaml: configs/validation_set_300_NIND_256_192_test_set_nind.yaml
weight_D1: 0.0
weight_D2: 0.0
weight_L1: 0.0
weight_MSE: null
weight_MSSSIM: 1.0
weight_SSIM: 0.0
